### ISSUE TITLE
The extension works well, but the shortcuts aren't a good choice

### ISSUE THREAD

**Issue by wazoox** [conradRz/FirefoxExtensionForSpeedingUpAllHTML5VideoAndAudio#3]
On Linux Ctrl+Shift+Y calls the download tool. So you can accelerate but never go back...

**Comment by conradRz** [comment]
Done and accepted to the Firefox store.

Extension should auto update on it's own.

https://github.com/conradRz/FirefoxExtensionForSpeedingUpAllHTML5VideoAndAudio/assets/26015206/b7076770-5753-4b6a-8bfb-390e6e671a90

Solved as above. To provide interface to change it other way, although doable, would require writing more code and debugging.

**Comment by wazoox** [comment]
Thank you, you saved my life :)
